### ISSUE TITLE
nested generics no more supported in 2.0.0

### ISSUE THREAD

**Issue by toschder** [klum-dsl/klum-ast#248]
DSL classes having nested generics like in this testcase: 

```
    def 'getElementType with nested generics'() {
        given:
        createClass('''
            class Dummy {
                Map<String, List<String>> authorizationRoles
            }

        ''')

        when:
        def dummy = getClass("Dummy")
        def value = DslHelper.getElementType(dummy, "authorizationRoles")

        then:
        noExceptionThrown()
    }

```
cant be used. 

Models will fail with something like:

```
Caused by: java.lang.IllegalArgumentException: ElementType java.util.List<java.lang.String> is neither class nor Wildcard
	at com.blackbuild.klum.ast.util.DslHelper.getElementType(DslHelper.java:103)
	at com.blackbuild.klum.ast.util.KlumInstanceProxy.doAddElementToMap(KlumInstanceProxy.java:422)
	at com.blackbuild.klum.ast.util.KlumInstanceProxy.addElementToMap(KlumInstanceProxy.java:414)
	at com.blackbuild.klum.ast.util.KlumInstanceProxy.lambda$addElementsToMap$13(KlumInstanceProxy.java:396)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at com.blackbuild.klum.ast.util.KlumInstanceProxy.addElementsToMap(KlumInstanceProxy.java:396)
	at com.blackbuild.klum.ast.util.KlumInstanceProxy.lambda$applyNamedParameters$2(KlumInstanceProxy.java:181)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at com.blackbuild.klum.ast.util.KlumInstanceProxy.applyNamedParameters(KlumInstanceProxy.java:181)
	at com.blackbuild.klum.ast.util.KlumInstanceProxy.apply(KlumInstanceProxy.java:165)
	at com.blackbuild.klum.ast.util.FactoryHelper.createAsTemplate(FactoryHelper.java:163)
	at com.blackbuild.klum.ast.util.TemplateManager.withTemplate(TemplateManager.java:62)
	at com.bmw.devci.jenkins.groups.DemoApp.run(DemoApp.groovy:26)
```

**Comment by pauxus** [comment]
related to #243
